import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

export const metadata = {
	title: "DnZ-ART",
	description: "Generated by Agile & Pixels",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="mx-4 md:mx-12 lg:mx-48">
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
